name: Build and Audit React Application

on:
  push:
    branches: [ main ] # Acesta va declanșa workflow-ul la fiecare push pe branch-ul 'main'
  workflow_dispatch: # Permite declanșarea manuală a workflow-ului din GitHub UI

jobs:
  build-and-audit:
    runs-on: ubuntu-latest # Rulează job-ul pe runner-ul GitHub 'ubuntu-latest'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Obține codul sursă din repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node' # Folosește ultima versiune stabilă de Node.js

    - name: Install Dependencies
      run: npm install # Instalează dependențele proiectului

    - name: Audit Dependencies
      run: npm audit --production # Efectuează un audit de securitate asupra dependențelor de producție

    - name: Build Project
      run: npm run build # Rulează comanda de build specifică proiectului tău React cu Vite
