name: Build and Audit React Project

on:
  push:
    branches: [ main ] # Sau schimbă cu numele branch-ului tău principal

jobs:
  build-and-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node' # Aceasta va utiliza ultima versiune stabilă de Node.js

    - name: Install Dependencies
      run: npm ci

    - name: Audit Dependencies
      run: npm audit --production # Verifică problemele de securitate în dependențele de producție

    - name: Build
      run: npm run build
