name: Build, Audit, and Deploy React Application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'

    - name: Install Dependencies
      run: npm install

    - name: Audit Dependencies
      run: npm audit --production

    - name: Build Project
      run: npm run build

    - name: Deploy to Another Repository
      run: |
        git config --global user.name 'Brebu Ciprian Alexandru Lucian'
        git config --global user.email 'brebu.ciprian@gmail.com'
        git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/Brebu/brebu.github.io.git
        cp -r build/* your-target-repo/
        cd your-target-repo
        git add .
        git commit -m "Deploy website"
        git push
